export const BEGIN = 'BEGIN'
export const CLEAR = 'CLEAR'
export const CANCEL = 'CANCEL'
export const CHOOSE = 'CHOOSE'
export const TYPE = 'TYPE'
export const LOAD_REQUEST = 'LOAD_REQUEST'
export const LOAD_SUCCESS = 'LOAD_SUCCESS'
export const LOAD_FAILURE = 'LOAD_FAILURE'
