---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_paths:
    - "**/__tests__/test_*.js"
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- "dist/"
- "examples/"
