highlighter: rouge
exclude: [Gemfile, Gemfile.lock, Procfile, config.rb, sass, .sass-cache, node_modules]
sass:
  style: compressed
  sass_dir: _sass
permalink: :title
navigation:
- header: User Guide
  section: userguide
  items:
  - label: Introduction
    url: ./index.html
  - label: Quick Start
    url: ./quickstart.html
  - label: State Management
    url: ./state.html
  - label: Server Requirements
    url: ./server.html
