highlighter: rouge
exclude: [Gemfile, Gemfile.lock, Procfile, config.rb, sass, .sass-cache, node_modules]
sass:
  style: compressed
  sass_dir: _sass
permalink: :title
navigation:
- header: User Guide
  section: user_guide
  items:
  - label: Introduction
    url: ./index.html
  - label: Quick Start
    url: ./quickstart.html
- header: Component Guide
  section: component_guide
  items:
  - label: Overview
    url: ./component_overview.html
  - label: State Management
    url: ./state.html
  - label: Component Filesystem
    url: ./filesystem.html
- header: Component Reference
  section: component_reference
  items:
  - label: Overview
    url: ./component_overview.html
  - label: Breadcrumbs
    url: ./breadcrumbs.html
  - label: Card
    url: ./card.html
  - label: Collection
    url: ./collection.html
  - label: Component
    url: ./component.html
  - label: Container
    url: ./container.html
  - label: Form
    url: ./form.html
  - label: Modal
    url: ./modal.html
  - label: Tabs
    url: ./tabs.html
