highlighter: rouge
exclude: [Gemfile, Gemfile.lock, Procfile, config.rb, sass, .sass-cache, node_modules]
baseurl: /reframe
sass:
  style: compressed
  sass_dir: _sass
permalink: :title
navigation:
- header: User Guide
  section: user_guide
  items:
  - label: Introduction
    url: /reframe/guides/user/index.html
  - label: Quick Start
    url: /reframe/guides/user/quickstart.html
- header: Component Guide
  section: component_guide
  items:
  - label: Overview
    url: /reframe/guides/components/overview.html
  - label: Component Filesystem
    url: /reframe/guides/components/filesystem.html
- header: Component Reference
  section: component_reference
  items:
  - label: Overview
    url: /reframe/reference/components/overview.html
  - label: Breadcrumbs
    url: /reframe/reference/components/breadcrumbs.html
  - label: Card
    url: /reframe/reference/components/card.html
  - label: Collection
    url: /reframe/reference/components/collection.html
  - label: Container
    url: /reframe/reference/components/container.html
  - label: Form
    url: /reframe/reference/components/form.html
  - label: Modal
    url: /reframe/reference/components/modal.html
  - label: Tabs
    url: /reframe/reference/components/tabs.html
  - label: Tasks
    url: /reframe/reference/components/tasks.html
- header: Control Reference
  section: control_reference
  items:
  - label: Overview
    url: /reframe/reference/controls/overview.html
  - label: Checkbox
    url: /reframe/reference/controls/checkbox.html
  - label: Checkboxes
    url: /reframe/reference/controls/checkboxes.html
  - label: Colorfield
    url: /reframe/reference/controls/colorfield.html
  - label: Filefield
    url: /reframe/reference/controls/filefield.html
  - label: Radios
    url: /reframe/reference/controls/radios.html
  - label: Select
    url: /reframe/reference/controls/select.html
  - label: Tablefield
    url: /reframe/reference/controls/tablefield.html
  - label: Textarea
    url: /reframe/reference/controls/textarea.html
  - label: Textfield
    url: /reframe/reference/controls/textfield.html
- header: Utility Reference
  section: utility_reference
  items:
  - label: Overview
    url: /reframe/reference/utilities/overview.html
  - label: API
    url: /reframe/reference/utilities/api.html
  - label: Config
    url: /reframe/reference/utilities/config.html
  - label: Format
    url: /reframe/reference/utilities/format.html
  - label: Socket
    url: /reframe/reference/utilities/socket.html
