'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var SET_READY = exports.SET_READY = 'SET_READY';
var LOAD_FILES_REQUEST = exports.LOAD_FILES_REQUEST = 'LOAD_FILES_REQUEST';
var LOAD_FILES_SUCCESS = exports.LOAD_FILES_SUCCESS = 'LOAD_FILES_SUCCESS';
var LOAD_FILES_FAILURE = exports.LOAD_FILES_FAILURE = 'LOAD_FILES_FAILURE';
var ADD_FILE = exports.ADD_FILE = 'ADD_FILE';
var UPLOAD_BEGIN = exports.UPLOAD_BEGIN = 'UPLOAD_BEGIN';
var UPLOAD_PROGRESS = exports.UPLOAD_PROGRESS = 'UPLOAD_PROGRESS';
var UPLOAD_PROCESS_REQUEST = exports.UPLOAD_PROCESS_REQUEST = 'UPLOAD_PROCESS_REQUEST';
var UPLOAD_PROCESS_SUCCESS = exports.UPLOAD_PROCESS_SUCCESS = 'UPLOAD_PROCESS_SUCCESS';
var UPLOAD_PROCESS_FAILURE = exports.UPLOAD_PROCESS_FAILURE = 'UPLOAD_PROCESS_FAILURE';
var UPLOAD_SUCCESS = exports.UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
var UPLOAD_FAILURE = exports.UPLOAD_FAILURE = 'UPLOAD_FAILURE';
var REMOVE_FILE = exports.REMOVE_FILE = 'REMOVE_FILE';
var UPLOAD_COMPLETE = exports.UPLOAD_COMPLETE = 'UPLOAD_COMPLETE';