'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var LOAD_SESSION = exports.LOAD_SESSION = 'LOAD_SESSION';
var SHOW_SESSION_ERROR = exports.SHOW_SESSION_ERROR = 'SHOW_SESSION_ERROR';
var SHOW_APPLICATION = exports.SHOW_APPLICATION = 'SHOW_APPLICATION';
var SHOW_FLASH_MESSAGE = exports.SHOW_FLASH_MESSAGE = 'SHOW_FLASH_MESSAGE';
var DISMISS_FLASH_MESSAGE = exports.DISMISS_FLASH_MESSAGE = 'DISMISS_FLASH_MESSAGE';
var CLEAR_FLASH_MESSAGES = exports.CLEAR_FLASH_MESSAGES = 'CLEAR_FLASH_MESSAGES';