// @flow

export const SET_SECTIONS: string = 'SET_SECTIONS'
export const FETCH_SECTIONS_REQUEST: string = 'FETCH_SECTIONS_REQUEST'
export const FETCH_SECTIONS_SUCCESS: string = 'FETCH_SECTIONS_SUCCESS'
export const FETCH_SECTIONS_FAILURE: string = 'FETCH_SECTIONS_FAILURE'
export const SET_DATA: string = 'SET_DATA'
export const FETCH_DATA_REQUEST: string = 'FETCH_DATA_REQUEST'
export const FETCH_DATA_SUCCESS: string = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_FAILURE: string = 'FETCH_DATA_FAILURE'
export const TOGGLE_BUSY: string = 'TOGGLE_BUSY'
export const SET_READY: string = 'SET_READY'
export const UPDATE_DATA: string = 'UPDATE_DATA'
export const SUBMIT_REQUEST: string = 'SUBMIT_REQUEST'
export const SUBMIT_SUCCESS: string = 'SUBMIT_SUCCESS'
export const SUBMIT_FAILURE: string = 'SUBMIT_FAILURE'
