//@flow

export const SET_READY: string = 'SET_READY'
export const LOAD_FILES_REQUEST: string = 'LOAD_FILES_REQUEST'
export const LOAD_FILES_SUCCESS: string = 'LOAD_FILES_SUCCESS'
export const LOAD_FILES_FAILURE: string = 'LOAD_FILES_FAILURE'
export const ADD_FILE: string = 'ADD_FILE'
export const UPLOAD_BEGIN: string = 'UPLOAD_BEGIN'
export const UPLOAD_PROGRESS: string = 'UPLOAD_PROGRESS'
export const UPLOAD_PROCESS_REQUEST: string = 'UPLOAD_PROCESS_REQUEST'
export const UPLOAD_PROCESS_SUCCESS: string = 'UPLOAD_PROCESS_SUCCESS'
export const UPLOAD_PROCESS_FAILURE: string = 'UPLOAD_PROCESS_FAILURE'
export const UPLOAD_SUCCESS: string = 'UPLOAD_SUCCESS'
export const UPLOAD_FAILURE: string = 'UPLOAD_FAILURE'
export const REMOVE_FILE: string = 'REMOVE_FILE'
export const UPLOAD_COMPLETE: string = 'UPLOAD_COMPLETE'
