export const SET_RECORDS = 'SET_RECORDS'
export const SET_PARAMS = 'SET_PARAMS'
export const SORT = 'SORT'
export const FILTER = 'FILTER'
export const FETCH_REQUEST = 'FETCH_REQUEST'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAILURE = 'FETCH_FAILURE'
