// @flow

export const SET_RECORDS: string = 'collection/SET_RECORDS'
export const APPEND_RECORDS: string = 'collection/APPEND_RECORDS'
export const TOGGLE_FILTERS: string = 'collection/TOGGLE_FILTERS'
export const CHANGE_LAYOUT: string = 'collection/CHANGE_LAYOUT'
export const SELECT_ALL: string = 'collection/SELECT_ALL'
export const SELECT: string = 'collection/SELECT'
export const FETCH_COLUMNS_REQUEST: string = 'collection/FETCH_COLUMNS_REQUEST'
export const FETCH_COLUMNS_SUCCESS: string = 'collection/FETCH_COLUMNS_SUCCESS'
export const FETCH_COLUMNS_FAILURE: string = 'collection/FETCH_COLUMNS_FAILURE'
export const SET_COLUMNS: string = 'collection/SET_COLUMNS'
export const FETCH_RECORDS_REQUEST: string = 'collection/FETCH_RECORDS_REQUEST'
export const FETCH_RECORDS_SUCCESS: string = 'collection/FETCH_RECORDS_SUCCESS'
export const FETCH_RECORDS_FAILURE: string = 'collection/FETCH_RECORDS_FAILURE'
export const FILTER_RECORDS: string = 'collection/FILTER_RECORDS'
export const SORT_RECORDS: string = 'collection/SORT_RECORDS'
export const EXPORT_RECORDS: string = 'collection/EXPORT_RECORDS'
export const RELOAD_RECORDS: string = 'collection/RELOAD_RECORDS'
export const EXECUTE_BATCH_ACTION: string = 'collection/EXECUTE_BATCH_ACTION'
